### ISSUE TITLE
loading anaconda module doesn't work 

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#6] opened 2019-08-17 15:00 UTC
Not finding the anaconda module in obs_prep jjob.

**Comment by flampouris** [comment] 2019-08-17 15:32
I think that the problem is more general, the information from places.yaml is not communicated correctly.

**Comment by guillaumevernieres** [comment] 2019-08-17 15:50
Probably, but that seems simpler that that. I can't load your anaconda:

$ module purge
$ module use -a /home/Stylianos.Flampouris/modulefiles/anaconda
$ module load anaconda/2019.08.07
Lmod has detected the following error:  The following module(s) are unknown: "anaconda/2019.08.07"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "anaconda/2019.08.07"

Also make sure that all modulefiles written in TCL start with the string #%Module

**Comment by flampouris** [comment] 2019-08-17 16:01
I have to different ideas:

1. at the top of the script, #!/bin/bash, it needs “-l” 

2. I screwed somehow the permissions

Ps I am writing from my phone now on my way to a hike.

**Comment by guillaumevernieres** [comment] 2019-08-17 16:04
No need to work today @flampouris ! Just adding to the todo list as I jack my way through the workflow!

**Comment by flampouris** [comment] 2019-08-22 18:25
Fixed on the way loading the modulefiles

module use -a /home/Stylianos.Flampouris/modulefiles/ 

The fix is at the PR_ForObs

**Closed as completed** 2019-08-22 22:17 UTC
